[programs.localnet]
gem_bank = "BfVyiGiftx9ZTpzgjDBNKe56ie6aFCMuVRNFa15wo7Yp"
gem_farm = "4fiPCtdqvoZMkz99voSNpvatNSrm1adQiwkxYKt5NxyS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/jskim/.config/solana/gemfarm.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

#[test]
#startup_wait = 100000

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./tests/programs/metaplex_token_metadata.so"